name: Sync GIOS Data to Azure SQL

on:
  schedule:
    - cron: "0 * * * *"   # co godzinÄ™
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ODBC driver for SQL Server
        run: |
          sudo su
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
          exit
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run GIOS sync script
        env:
          AZURE_SERVER: ${{ secrets.AZURE_SERVER }}
          AZURE_DB: ${{ secrets.AZURE_DB }}
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PASS: ${{ secrets.AZURE_PASS }}
        run: python backend/fetch_gios_to_sql.py
